<a href="https://colab.research.google.com/github/MaxiPerrone/redes_neuronales/blob/main/1_Neurona_MP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
class MPNueron:
  def __init__(self):
    self.threshold = None

  def model(self, x):
    z = sum(x)
    return (z >= self.threshold)

  def predict(self, X):
    Y = []
    for x in X:
      result = self.model(x)
      Y.append(result)
    return np.array(Y)

In [ ]:
mp_neuron = MPNueron()

In [ ]:
mp_neuron.threshold = 3;

In [ ]:
mp_neuron.predict([[1, 0, 0, 0], [1, 1, 1, 1], [1, 1, 1, 0]])

array([False,  True,  True])

In [ ]:
mp_neuron.threshold = 1;

In [ ]:
mp_neuron.predict([[1, 0, 0, 0], [1, 1, 1, 1], [1, 1, 1, 0]])

array([ True,  True,  True])

In [ ]:
mp_neuron.threshold = 5;

In [ ]:
mp_neuron.predict([[1, 0, 0, 0], [1, 1, 1, 1], [1, 1, 1, 0]])

array([False, False, False])